name: Release NPM

on:
  push:
    branches: [release/*]

jobs:
  publish-npm:
    name: Publish NPM module
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - uses: mymindstorm/setup-emsdk@v14
        with:
          # See https://github.com/tree-sitter/tree-sitter/blob/master/cli/emscripten-version
          version: 2.0.24
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm install-test
      - uses: cucumber/action-publish-npm@v1.1.1
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
